### ISSUE TITLE
Overlay in lineageos 18.1

### ISSUE THREAD

**Issue by Lamiwil** [greenflash1986/UnifiedNlpOverlay#1]
Hello,
I am sorry to contact you by opening an issue, but I didn't find an other way.

I am trying to get unifiednlp working with lineageos 18.1. I can't get UnifiedNlp resgistred in system. I placed UnifiedNlp.apk is /system/priv-app/UnifiedNlp with the right security permission, org.microg.nlp.xml in /etc/permissions with right secutity permission. However, I did not place UnifiedNlpOverlay.apk in /system/vendor/overlay because you did not provide it and I did not manage to build it... Can you upload  UnifiedNlpOverlay.apk or help me to build it ? I thank you in advance.
Best regards,

**Comment by greenflash1986** [comment]
Hi @Lamiwil 
I clarified the readme: there is already a release. I guess you can use it. But I updated the readme with build instructions as well.
